#!/bin/bash
# Timelapse controller for Raspberry Pi

IMAGEDIR=imagesCONTINUOUS
DELAY=55
# Note: The total time interval between images is 
# approximately $DELAY+5 seconds, since the camera module 
# takes approximately 5 seconds to calibrate i
while getopts “i:d:” OPTION
do
     case $OPTION in
         i)
             IMAGEDIR=$OPTARG
             ;;
         d)
             DELAY=$OPTARG
             ;;
     esac
done

PROJECTDIR=/home/pi/techxtimelapse
# mkdir $PROJECTDIR/$IMAGEDIR

# As of 13 Dec 2013,
# -sh, -co, -sa range from -100 to 100. Default at 0
# -br ranges from 0 to 100. Default at 50
# -ev officially ranges from -10 to 10 with a default at 0. However when you push to -20 you still see results.
# options for -ex: auto, night, nightpreview, backlight, spotlight, sports, snow, beach, verylong, fixedfps, antishake, fireworks
# options for -awb: off, auto, sun, cloudshade, tungsten, fluorescent, incandescent, flash, horizon

while true;
do
	filename=$(date +"%Y%m%d_%H%M-%S").jpg
        raspistill --metering matrix --nopreview --output $PROJECTDIR/$IMAGEDIR/$filename
	sleep $DELAY
done
